### PR TITLE
Changes to pcap index file

### LINKED ISSUE #37: Failure to symlink on Windows: "A required privilege is not held by the client"
Currently `brimcap load` seems to fail on Windows. While testing the `v0.0.1` release artifact, I attempted my first load and found:

```
C:\Users\Phil\Downloads\brimcap-v0.0.1.windows-amd64\brimcap>.\brimcap.exe load -s wrccdc -root c:\brimcap-root \users\phil\Desktop\wrccdc.2018-03-23.010014000000000.pcap
error writing brimcap root: symlink C:\users\phil\Desktop\wrccdc.2018-03-23.010014000000000.pcap c:\brimcap-root\wrccdc.2018-03-23.010014000000000.pcap: A required privilege is not held by the client.
```

I did some sleuthing and found articles like [https://www.wintellect.com/non-admin-users-can-now-create-symlinks-windows-10/](https://www.wintellect.com/non-admin-users-can-now-create-symlinks-windows-10/) that seem to imply that on current Windows desktops it's not a given that this would work. I then confirmed that if I right-clicked my Command Prompt to "Run as Administrator", the command did indeed work ok. But I'm guessing it would not be reasonable to expect users to only run Brimcap (or Brim itself, if it's the one that will be invoking Brimcap) in admin mode.

### PR DESCRIPTION
**Pull request by mattnibs**
A couple of changes to how a pcap index file is saved:

1. Use the hash of a file for the filename, to avoid saving pcaps with the same
name but different file contents.
2. Get rid of the symlink and include the original pcap path in the same json
file where the index is saved. This had to be done since windows hows trouble
resolving a symlink when the user is not an Administrator:
https://www.wintellect.com/non-admin-users-can-now-create-symlinks-windows-10/

Closes #37

### CODE REVIEW

File: cmd/brimcap/index/command.go [hunk 1]
```diff
@@ -83,22 +83,23 @@ func (c *Command) Exec(args []string) (err error) {
...
 	}
 
-	f := os.Stdin
-	if c.inputFile != "-" {
-		f, err = os.Open(c.inputFile)
-		if err != nil {
-			return err
+	if c.rootflags.IsSet {
+		if c.inputFile == "-" {
+			return errors.New("cannot write pcap from stdin to BRIMCAP_ROOT")
```
Comment (nwt) [inline cmd/brimcap/index/command.go:88]:
```suggestion
			return errors.New("cannot write pcap from stdin to brimcap root")
```

File: cmd/brimcap/load/command.go [hunk 2]
```diff
@@ -93,27 +93,34 @@ func (c *Command) Exec(args []string) (err error) {
...
+	pcapfile, err := cli.OpenFileArg(pcappath)
 	if err != nil {
 		root.DeletePcap(pcappath)
 		return err
 	}
 	defer pcapfile.Close()
 
+	ctx, cancel := signalctx.New(os.Interrupt)
+	defer cancel()
+
```
Comment (nwt) [inline cmd/brimcap/load/command.go:114]: Nit: Move this closer to `ctx`'s use.

File: root.go [hunk 3]
```diff
@@ -29,39 +32,33 @@ type Search struct {
 
 type Root string
 
-// AddPcap adds the pcap path to the BRIMCAP_ROOT, meaning a symlink for the pcap is
-// added to the root directory along with an index of the pcap.
-func (r Root) AddPcap(path string, limit int, warner zbuf.Warner) (nano.Span, error) {
-	f, err := os.Open(path)
+// AddPcap adds the pcap path to the BRIMCAP_ROOT, XXX
```
Comment (nwt) [inline root.go:35]:
```suggestion
// AddPcap adds the pcap path to the brimcap root.
```

File: root.go [hunk 4]
```diff
@@ -29,39 +32,33 @@ type Search struct {
...
-	if err := pkgfs.MarshalJSONFile(index, r.IndexPath(path), 0644); err != nil {
-		r.DeletePcap(path)
-		return err
-	}
-	return nil
+	return index.Span(), os.WriteFile(r.filepath(hash), b, 0600)
+}
+
+func (r Root) filepath(hash hash.Hash) string {
+	name := "idx-" + base64.RawURLEncoding.EncodeToString(hash.Sum(nil)) + ".json"
```
Comment (nwt) [inline root.go:60]: Maybe say `const indexPrefix = "idx-"` and use it here and in `Root.Pcaps`?

**Review by nwt — APPROVED** [review]
