### PR TITLE
Analyzer process: configurable working directory

### LINKED ISSUE #16: Improve "brimcap analyze" error messaging & diagnostics
Since part of what we're trying to achieve with Brimcap is to make it easier for users to bring their own custom Zeek/Suricata, it'll be important that we surface details with problems in such tools when they're invoked via `brimcap analyze` during pcap processing.

To cite a specific example, here's what a macOS user sees at the moment with `brimcap` commit `688a7f5` and Homebrew-installed Zeek v4.0.0 and Suricata v6.0.2 when analyzing [https://archive.wrccdc.org/pcaps/2018/wrccdc.2018-03-23.010014000000000.pcap.gz:](https://archive.wrccdc.org/pcaps/2018/wrccdc.2018-03-23.010014000000000.pcap.gz:)

```
$ brimcap analyze -z ../wrccdc.pcap > /dev/null
1 warnings occurred while parsing log data:
    /var/folders/yn/jbkxxkpd4vg142pc3_bd_krc0000gn/T/brimcap-2408807547/eve.json: duplicate field subject: x1
```

There are known issues at play here, specifically that Suricata v6 is generating bad output (#13) and Zed could stand to provide more detail about where the "duplicate field" problem arose in the data (brimdata/zed#2452). But putting those aside, some things that would have improved the user experience if it had arisen in the wild:

1.  Provide a way for the user to see the stdout and stderr of the Zeek/Suricata processes invoked via `brimcap analyze` so the user knows whether those pieces ran healthy. In this case they did, but users might encounter any number of speedbumps if they're iteratively tweaking configs or adding customizations to these systems.
2.  Make it clear if the choke happened downstream of the invoked processes, such as in this case where it happened in the Zed shaping step.
3.  Have the ability to leave behind the logs generated by Zeek/Suricata so the user can examine them. In this case, the user could have used `zq` or other JSON processing tools on the raw EVE JSON output to isolate which lines had the duplicate field.
4.  Show the command lines that `suricata analyze` used when invoking these processes, so the user can easily repeat this in their debug steps.

In summary, I expect our `brimcap analyze` support statement will be something like "if it doesn't 'just work', repeat the individual steps performed by `brimcap analyze` and see where it goes wrong". In this regard, having a debug mode that's as transparent as possible will be very helpful.

### PR DESCRIPTION
**Pull request by mattnibs**
Add workdir field to analyzer configuration. If workdir is set, the analyzer
process usees this directory as the current working directory for the executed
process.

Closes #16

### CODE REVIEW

File: analyzer/analyzer.go [hunk 1]
```diff
@@ -27,7 +27,7 @@ type analyzer struct {
 	cancel   context.CancelFunc
 	config   Config
 	ctx      context.Context
-	logdir   string
+	wd       string
```
Comment (nwt) [inline analyzer/analyzer.go:30]: Nit: `wd` is pretty cryptic, so call it `workdir`, which isn't much longer.

File: analyzer/analyzer.go [hunk 2]
```diff
@@ -94,10 +94,12 @@ func (p *analyzer) run() (err error) {
 		}
 	}
 
-	logdir, err := os.MkdirTemp("", "brimcap-")
-	if err != nil {
-		close(p.procDone)
-		return err
+	logdir := p.config.WorkDir
```
Comment (nwt) [inline analyzer/analyzer.go:97]: NIt: Calling this logdir and workdir is confusing, so pick one.

File: analyzer/analyzer.go [hunk 3]
```diff
@@ -158,8 +160,11 @@ func (p *analyzer) Close() (err error) {
 	if p.tailer != nil {
 		err = p.tailer.Close()
 	}
-	if err2 := os.RemoveAll(p.logdir); err == nil {
-		err = err2
+
+	if p.config.WorkDir == "" {
+		if err2 := os.RemoveAll(p.wd); err == nil {
```
Comment (nwt) [inline analyzer/analyzer.go:165]: Wrap the other `os.RemoveAll` calls like this.

Comment (mattnibs) [reply analyzer/analyzer.go:165]: All the other ones are called when an error is returned and so its part of an abort. Not interested in the error it would return.

Comment (mattnibs) [reply analyzer/analyzer.go]: Oh nvm, you are right!

File: analyzer/config.go [hunk 4]
```diff
@@ -16,6 +16,11 @@ type Config struct {
 	Shaper     string         `yaml:"shaper"`
 	StdoutPath string         `yaml:"stdout"`
 	StderrPath string         `yaml:"stderr"`
+	// WorkDir if set uses the provided directory as the working directory for
+	// the launched analyzer process. Normally a temporary directory is created
+	// then deleted when the process is complete, if WorkDir is set the working
```
Comment (nwt) [inline analyzer/config.go:21]:
```suggestion
	// then deleted when the process is complete. If WorkDir is set the working
```

File: cmd/brimcap/ztests/analyze-process-error.yaml [hunk 5]
```diff
@@ -1,7 +1,5 @@
 script: |
-  export PATH=$(pwd):$PATH
-  chmod +x errorproc.sh
-
+  chmod +x errorproc.sh && mkdir wd && cp errorproc.sh wd
```
Comment (nwt) [inline cmd/brimcap/ztests/analyze-process-error.yaml:2]:
```suggestion
  chmod +x errorproc.sh && mkdir wd && mv errorproc.sh wd
```

**Review by nwt — APPROVED** [review]
